# -*- coding: utf-8 -*-
"""Prova 1º Bimestre - Programação em Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX8eiir-GGrufLGXM-_ADhWE5bIBcH9s
"""

import pandas as pd
import plotly.express as px

fumas = pd.read_excel("/content/smoking.xlsx")

fumasdf = pd.DataFrame(fumas)

fumasdf = fumasdf.rename(columns={'marital_status': 'Estado Civil', 'highest_qualification' : 'Grau de Escolaridade', 'region' : 'Região', 'smoke' : 'Fumas?', 'amt_weekends' : 'Cigarros por Dia no FDS', 'amt_weekdays' : 'Cigarros por dia durante a semana', 'type' : 'Tipo de cigarro', 'gross_income' : 'Renda Bruta', 'gender' : 'Gênero', 'age' : 'Idade', 'nationality' : 'Nacionalidade', 'ethnicity' : 'Etnicidade'})

fumasdf = pd.DataFrame(fumasdf)

fumasdf

grafico_fumas1 = px.bar(
    fumasdf,
    x = 'Fumas?',
    text_auto=True,
    title = 'Quantidade dos Fumantes e Não Fumantes'
)

grafico_fumas1

FiltroFumantes = fumasdf[fumasdf['Fumas?'] == 'Yes']

FiltroFumantes

grafico_fumas2 = px.bar(
    FiltroFumantes,
    x = 'Grau de Escolaridade',
    text_auto=True,
    title = 'Dados dos Fumantes por Escolaridade'
)

grafico_fumas2

IdadeFumantes = FiltroFumantes['Idade'].value_counts()

IdadeFumantes = pd.DataFrame(IdadeFumantes)

IdadeFumantes = IdadeFumantes.sort_values(by='Idade', ascending=True)

IdadeFumantes

grafico_fumas3 = px.bar(
    IdadeFumantes,
    y = 'count',
    text_auto=True,
    title = 'Dados dos Fumantes por Idade'
)

grafico_fumas3

RendaFumantes = FiltroFumantes['Renda Bruta'].value_counts()

RendaFumantes = pd.DataFrame(RendaFumantes)

RendaOrdenada = ['Unknown', 'Refused', 'Under 2,600', '2,600 to 5,200', '5,200 to 10,400', '10,400 to 15,600', '15,600 to 20,800', '20,800 to 28,600', '28,600 to 36,400', 'Above 36,400']

RendaFumantes = RendaFumantes.reindex(RendaOrdenada)

RendaFumantes

grafico_fumas4 = px.bar(
    RendaFumantes,
    y = 'count',
    text_auto=True,
    title = 'Dados dos Fumantes por Renda'
)

grafico_fumas4

TipoCigas = FiltroFumantes['Tipo de cigarro'].value_counts()

TipoCigas = pd.DataFrame(TipoCigas)

TipoCigas

grafico_fumas5 = px.bar(
    TipoCigas,
    y = 'count',
    text_auto=True,
    title = 'Dados de Tipos de Cigarros'
)

grafico_fumas5

!pip install -q streamlit

!npm install localtunnel

import urllib

print("SENHA/Enpoint IP para o túnel local:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("/n"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from Prova import *
# 
# st.set_page_config(layout='wide')
# st.title("Fumas no UK  :uk::speaking_head_in_silhouette::smoking:")
# 
# st.sidebar.title('Filtro de Idade')
# 
# filtro_idade = st.sidebar.multiselect(
#     'Selecione as Idades',
#     FiltroFumantes['Idade'].unique())
# 
# if filtro_idade:
#     FiltroFumantes = FiltroFumantes[FiltroFumantes['Idade'].isin(filtro_idade)]
# 
# aba1, aba2 = st.tabs(['Dados Principais', 'Dados Categorizados'])
# 
# with aba1:
#   coluna1, coluna2 = st.columns(2)
# 
# with coluna1:
#   st.plotly_chart(grafico_fumas1, use_container_width=True)
# 
# with coluna2:
#   st.plotly_chart(grafico_fumas5, use_container_width=True)
# 
# with aba2:
#   coluna3, coluna4 = st.columns(2)
# 
# with coluna3:
#   st.metric('Total de Fumantes', (FiltroFumantes['Idade'].count()))
#   st.plotly_chart(grafico_fumas3, use_container_width=True)
#   st.plotly_chart(grafico_fumas2, use_container_width=True)
# 
# with coluna4:
#   st.plotly_chart(grafico_fumas4, use_container_width=True)
# 
#

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501