# -*- coding: utf-8 -*-
"""projeto_criptografia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Z1rh4eTuGOC1I7LxC9XheDU-5J83FMY
"""

!pip install pycryptodome

from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad
import base64
from google.colab import files

def criptografia(chave, caminho_arquivo, caminho_arquivo_criptografado):
    with open(caminho_arquivo, 'rb') as arquivo:
        leitura = arquivo.read()

    criarAES = AES.new(chave, AES.MODE_ECB)
    alteraçãopad = pad(leitura, AES.block_size)
    arquivovascaino = criarAES.encrypt(alteraçãopad)

    with open(caminho_arquivo_criptografado, 'wb') as arquivo:
        arquivo.write(arquivovascaino)

chave = get_random_bytes(16)

try :
  upload = files.upload()

  for arquivinho in upload.keys():
      with open(arquivinho, 'wb') as arquivo:
          arquivo.write(upload[arquivinho])

      arquivo_extensão = arquivinho + '.teste'
      criptografia(chave, arquivinho, arquivo_extensão)
      print("Arquivo criptografado salvo como:", arquivo_extensão, "nos arquivos do Colab.")

  chave_base64 = base64.b64encode(chave).decode('utf-8')
  print("Sua chave de descriptografia é:", chave_base64, "Salve ela imediatamente.")

except KeyboardInterrupt:
  print("O usuário foi interrompeu o procedimento.")

"""_________________________________________________________________________________________________________

"""

def descriptografar_arquivo(chave, caminho_arquivo_criptografado, caminho_arquivo_descriptografado):
    with open(caminho_arquivo_criptografado, 'rb') as arquivo:
        leitura = arquivo.read()

    criarAES = AES.new(chave, AES.MODE_ECB)
    arquivo = criarAES.decrypt(leitura)
    arquivo_original = unpad(arquivodesvascainado, AES.block_size)

    with open(caminho_arquivo_descriptografado, 'wb') as arquivo:
        arquivo.write(arquivo_original)

try:
  arquivão = input("Digite o caminho do arquivo criptografado: ")

  if arquivão.endswith('.teste'):
    arquivo_sem_cript = arquivão[:-6]
    arquivo_sem_extensão = 'descriptografado_' + arquivo_sem_ext.split('/')[-1]

  else:
    arquivo_sem_extensão = arquivão

  chave_base64 = input("Digite a chave de descriptografia: ")
  chave = base64.b64decode(chave_base64)

  descriptografar_arquivo(chave, arquivão, arquivo_sem_extensão)
  print("Arquivo descriptografado salvo em:", arquivo_sem_extensão)

except (ValueError, FileNotFoundError) as e:
  print(f"Chave incorreta. Devido ao erro: {e}")
except KeyboardInterrupt:
  print("O usuário foi otário e parou o procedimento.")
